image: node:20-bookworm

variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
  - apt-get update -qq && apt-get install -y -qq xvfb fvwm libnss3 
  - su -c 'mkdir -p ~/tmp' node

ci:
  script:
    # gitlab images run as root in container
    - su -c whoami node
    - su -c 'npm install --python=python3 --unsafe-perm' node
    - su -c 'xvfb-run bash -c "fvwm& npm run ci"' node
  coverage: '/^All files[^\d]*(\d+[.\d]*)/'
  artifacts:
    name: coverage
    paths:
      - coverage/
