image: node:20-bookworm

variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
  - apt-get update -qq && apt-get install -y -qq xvfb fvwm libnss3
  - mkdir -p ~/tmp

ci:
  script:
    # gitlab images run as root in container
    - whoami
    - npm install --python=python3 --unsafe-perm
    - xvfb-run bash -c 'fvwm& sudo -u node npm run ci'
  coverage: '/^All files[^\d]*(\d+[.\d]*)/'
  artifacts:
    name: coverage
    paths:
      - coverage/
