build:
  services:
    - docker:dind
  image: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - >
      docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA - <<EOT
        FROM node:20-bookworm
        ENV DEBIAN_FRONTEND noninteractive
        RUN apt install -y wget
        RUN wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub > /etc/apt/trusted.gpg.d/google.asc \
            && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
        RUN apt update -qq && apt install -y -qq xvfb fvwm google-chrome-stable
        USER node
      EOT
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

ci:
  needs: [build]
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script:
    - whoami
    - mkdir -p ~/tmp
  script:
    - npm install
    - xvfb-run bash -c 'fvwm& npm run ci'
  coverage: '/^All files[^\d]*(\d+[.\d]*)/'
  artifacts:
    name: coverage
    paths:
      - coverage/
