= webauthn-perk {nbsp}{nbsp}{nbsp} image:https://gitlab.com/davedoesdev/webauthn-perk/badges/master/pipeline.svg[pipeline status,link=https://gitlab.com/davedoesdev/webauthn-perk/pipelines] image:https://gitlab.com/davedoesdev/webauthn-perk/badges/master/coverage.svg[coverage report,link="https://gitlab.com/davedoesdev/webauthn-perk/builds/artifacts/master/download?job=ci"] image:http://localhost:4874/npm/v/@davedoesdev/webauthn-perk.svg?registry_uri=http://localhost:4873[NPM version,link=http://localhost:4873/#/detail/@davedoesdev/webauthn-perk]
:prewrap!:

https://www.fastify.io/[Fastify] plugin for supporting the https://www.w3.org/TR/webauthn/[Web Authentication]
Perk pattern (thanks to https://github.com/emlun[Emil Lundberg] for https://github.com/w3c/webauthn/issues/902#issuecomment-388223929[rephrasing] my original description):

1. Alice (an admin) chooses an unguessable ID.
2. Alice configures `webauthn-perk` on her Web server with the ID.
3. Alice uses her Web browser to visit a URL on her Web server which contains the ID.
4. Alice uses the Web Authentication API to sign a challenge generated on her server.
5. The signature and Alice's public key are sent to her server.
6. Alice's server verfies the signature.
7. Alice's server associates her public key with the ID.
8. Alice uses client-side script to generate an unsigned JWT containing claims of her choosing.
9. Alice uses the Web Authentication API to generate a signed assertion, with the unsigned JWT as the challenge.
10. Alice sends the assertion to ordinary user Bob (by some means).
11. Bob uses his Web browser to visit a well-known URL on Alice's Web server.
12. Bob presents the assertion to Alice's server.
13. Alice's server verifies the assertion using Alice's public key.
14. Bob receives a perk, i.e. Alice's Web server provides some service to Bob.

== Registering

Register `webauthn-perk` with Fastify as normal. The available options and their defaults are described below.

[source,javascript]
----
fastify.register(require('webauthn-perk'), {
    webauthn_perk_options: {
        authorize_jwt_options: {
            // You should override db_dir
            db_dir: 'node_modules/pub-keystore/pouchdb/store/pub-keys',
            db_type: 'pouchdb',
            db_for_update: true,
            no_updates: true,
            WEBAUTHN_MODE: true
            // See https://github.com/davedoesdev/authorize-jwt#moduleexportsconfig-cb for more options
        },
        cred_options: {
            valid_ids: [], // List of unguessable IDs (strings)
            prefix: '/cred', // Unguessable IDs are prefixed with this plus /
            challenge_timeout: 60000, // Server challenges expire after this (ms)
            fido2_options: {
                user: {
                    // You can override these but they'll only be used if your
                    // authenticator supports storing user handles
                    name: 'Anonymous User',
                    displayName: 'Anonymous User',
                    id: 'Anonymous User'
                },
                new_options: {
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html
                },
                attestation_options: {
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html#attestationOptions
                },
                assertion_options: {
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html#assertionOptions
                },
                attestation_expectations: {
                    origin: `https://${request.headers.host}`,
                    factor: 'either'
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html#attestationResult
                },
                assertion_expectations: {
                    origin: `https://${request.headers.host}`,
                    factor: 'either',
                    prevCounter: 0
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html#assertionResult
                },
                async function complete_assertion_expectations(assertion, assertion_expectations) {
                    // If you want to change assertion_expectations depending on the assertion,
                    // override this function.
                    return assertion_expectations;
                }
            },
            secure_session_options: {
                // See https://github.com/mcollina/fastify-secure-session
            }
        },
        perk_options: {
            prefix: '/perk', // Well-known path for presenting assertions is this plus /
            assertion_expectations: {
                origin: `https://${request.headers.host}`,
                factor: 'either',
                prevCounter: 0
                // See https://apowers313.github.io/fido2-lib/Fido2Lib.html#assertionResult
                // authorize_jwt_options.complete_webauthn_token can also supply these
            },
            handler: function (info, request, reply) {
                // This function is called after an assertion is successfully verified.
                // You must override this or perk requests will fail.
                // request and reply are standard Fastify objects and your function
                // is treated as a standard route handler.
                // info contains payload, uri, rev and assertion_result properties
                // as described for the cb parameter here:
                // https://github.com/davedoesdev/authorize-jwt#authorizejwtprototypeauthorizeauthz_token-allowed_algs-cb
                throw new Error('missing handler');
            }
        }
    }
});
----

== Routes

The following routes will be added to your server. All request and response bodies should be JSON-encoded.

* `/cred/*id*/` for each `*id*` in `webauthn_perk_options.cred_options.valid_ids`
** GET requests:
*** If no public key is associated with `*id*` then the response status is 404 and the body will be an
    https://apowers313.github.io/fido2-lib/Fido2Lib.html#attestationOptions[attestation options] object
    containing a challenge and other parameters necessary for calling `navigator.credentials.create` in a browser.
*** If a public key has been associated with `*id*` then the response status is 200 and the body will contain
    the credential ID (identifies the private key to the browser), the issuer ID (identifies the public key
    to the server) and a challenge (for verifying using a POST request, see below).
** PUT requests:
*** The request body should contain an https://apowers313.github.io/fido2-lib/Fido2Lib.html#attestationResult[attestation
    result] generated by `navigator.credentials.create` in a browser.
*** If the attestation result does not verify or is invalid then the response status is 400.
*** If a public key is already associated with `*id*` then the response status is 409.
*** Otherwise the public key contained in the attestation result is associated with `*id*` and
    the response status is 200. The body will contain the credential ID (identifies the private
    key to the browser) and the issuer ID (identifies the public key to the server).
** POST requests:
*** The request body should contain an https://apowers313.github.io/fido2-lib/Fido2Lib.html#assertionResult[assertion
    result] generated by `navigator.credentials.get` in a browser. You should have made a GET request
    previously to obtain the challenge required by `navigator.credentials.get`.
*** If no public key is associated with `*id*` then the response status is 404.
*** If the assertion result does not verify using the public key associated with `*id*` or is invalid
    then the response status is 400.
*** Otherwise the response status is 204 and the body is empty.
*** Use this function to check you have access to the private key which corresponds to the public key
    that the server has associated with `*id*`.
