= webauthn-perk {nbsp}{nbsp}{nbsp} image:https://gitlab.com/davedoesdev/webauthn-perk/badges/master/pipeline.svg[pipeline status,link=https://gitlab.com/davedoesdev/webauthn-perk/pipelines] image:https://gitlab.com/davedoesdev/webauthn-perk/badges/master/coverage.svg[coverage report,link="https://gitlab.com/davedoesdev/webauthn-perk/builds/artifacts/master/download?job=ci"] image:http://localhost:4874/npm/v/@davedoesdev/webauthn-perk.svg?registry_uri=http://localhost:4873[NPM version,link=http://localhost:4873/#/detail/@davedoesdev/webauthn-perk]
:prewrap!:

https://www.fastify.io/[Fastify] plugin for supporting the https://www.w3.org/TR/webauthn/[Web Authentication]
Perk pattern (thanks to https://github.com/emlun[Emil Lundberg] for https://github.com/w3c/webauthn/issues/902#issuecomment-388223929[rephrasing] my original description):

1. Alice (an admin) chooses an unguessable ID.
2. Alice configures `webauthn-perk` on her Web server with the ID.
3. Alice uses her Web browser to visit a URL on her Web server which contains the ID.
4. Alice uses the Web Authentication API to sign a challenge generated on her server.
5. The signature and Alice's public key are sent to her server.
6. Alice's server verfies the signature.
7. Alice's server associates her public key with the ID.
8. Alice uses client-side script to generate an unsigned JWT containing claims of her choosing.
9. Alice uses the Web Authentication API to generate a signed assertion, with the unsigned JWT as the challenge.
10. Alice sends the assertion to ordinary user Bob (by some means).
11. Bob uses his Web browser to visit a well-known URL on Alice's Web server.
12. Bob presents the assertion to Alice's server.
13. Alice's server verifies the assertion using Alice's public key.
14. Bob receives a perk, i.e. Alice's Web server provides some service to Bob.

== Example

1. Run link:test/example.js[] on your server (`node -r esm test/example.js`).

2. Visit the URL it displays in your WebAuthn-supporting browser. The source to
   this page is in link:test/fixtures/example.html[] and link:test/fixtures/example.js[].
   Either click through the certificate warnings or add link:test/keys/ca.crt[]
   to your browser's trusted certificate authorities.

3. Use your security token to register or authenticate.

4. Type in a message and click *Generate*.

5. You'll be shown another link. Open this in a different browser (doesn't have to
   support Webauthn).

6. You should see your message.

6. Repeat with different messages as you like.

== Registering

Register `webauthn-perk` with Fastify as normal. The available options and their defaults are described below.

[source,javascript]
----
import webauthn_perk from 'webauthn-perk';
fastify.register(webauthn_perk, {
    webauthn_perk_options: {
        authorize_jwt_options: {
            // You should override db_dir
            db_dir: 'node_modules/pub-keystore/pouchdb/store/pub-keys',
            db_type: 'pouchdb',
            db_for_update: true,
            no_changes: true,
            no_updates: true,
            WEBAUTHN_MODE: true,
            // See https://github.com/davedoesdev/authorize-jwt#moduleexportsconfig-cb for more options
            async on_authz(unused_authz) {
                // Receives the AuthorizeJWT instance once it's constructed (see https://github.com/davedoesdev/authorize-jwt)
            }
        },
        cred_options: {
            valid_ids: [], // List of unguessable IDs (strings)
            prefix: '/cred', // Unguessable IDs are prefixed with this plus /
            challenge_timeout: 60000, // Server challenges expire after this (ms)
            fido2_options: {
                user: {
                    // You can override these but they'll only be used if your
                    // authenticator supports storing user handles
                    name: 'Anonymous User',
                    displayName: 'Anonymous User',
                    id: 'Anonymous User'
                },
                new_options: {
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html
                },
                attestation_options: {
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html#attestationOptions
                },
                assertion_options: {
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html#assertionOptions
                },
                attestation_expectations: {
                    origin: `https://${request.headers.host}`,
                    factor: 'either'
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html#attestationResult
                },
                assertion_expectations: {
                    origin: `https://${request.headers.host}`,
                    factor: 'either',
                    prevCounter: 0
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html#assertionResult
                },
                async function complete_assertion_expectations(assertion, assertion_expectations) {
                    // If you want to change assertion_expectations depending on the assertion,
                    // override this function.
                    return assertion_expectations;
                }
            },
            secure_session_options: {
                // See https://github.com/mcollina/fastify-secure-session
                // You must supply a key.
            }
        },
        perk_options: {
            prefix: '/perk', // Well-known path for presenting assertions is this plus /
            fido2_options: {
                assertion_expectations: {
                    origin: `https://${request.headers.host}`,
                    factor: 'either',
                    prevCounter: 0
                    // See https://apowers313.github.io/fido2-lib/Fido2Lib.html#assertionResult
                    // authorize_jwt_options.complete_webauthn_token can also supply these
                },
            },
            handler: function (info, request, reply) {
                // This function is called after an assertion is successfully verified.
                // You must override this or perk requests will fail.
                // request and reply are standard Fastify objects and your function
                // is treated as a standard route handler.
                // info contains payload, uri, rev and assertion_result properties
                // as described for the cb parameter here:
                // https://github.com/davedoesdev/authorize-jwt#authorizejwtprototypeauthorizeauthz_token-allowed_algs-cb
                throw new Error('missing handler');
            }
        }
    }
});
----

== Routes

The following routes will be added to your server. All request and response bodies should be JSON-encoded.

* `/cred/*id*/` for each `*id*` in `webauthn_perk_options.cred_options.valid_ids`
** GET requests:
*** If no public key is associated with `*id*` then the response status is 404 and the body will be an
    https://apowers313.github.io/fido2-lib/Fido2Lib.html#attestationOptions[attestation options] object
    containing a challenge and other parameters necessary for calling `navigator.credentials.create` in a browser.
*** If a public key has been associated with `*id*` then the response status is 200 and the body will contain
    the credential ID (identifies the private key to the browser), the issuer ID (identifies the public key
    to the server) and a challenge (for verifying using a POST request, see below).
** PUT requests:
*** The request body should contain an https://apowers313.github.io/fido2-lib/Fido2Lib.html#attestationResult[attestation
    result] generated by `navigator.credentials.create` in a browser. You should have made a GET request
    previously to obtain the challenge required by `navigator.credentials.create`.
*** If the attestation result does not verify or is invalid then the response status is 400.
*** If a public key is already associated with `*id*` then the response status is 409.
*** Otherwise the public key contained in the attestation result is associated with `*id*` and
    the response status is 200. The body will contain the credential ID (identifies the private
    key to the browser) and the issuer ID (identifies the public key to the server).
** POST requests:
*** The request body should contain an https://apowers313.github.io/fido2-lib/Fido2Lib.html#assertionResult[assertion
    result] generated by `navigator.credentials.get` in a browser. You should have made a GET request
    previously to obtain the challenge required by `navigator.credentials.get`.
*** If no public key is associated with `*id*` then the response status is 404.
*** If the assertion result does not verify using the public key associated with `*id*` or is invalid
    then the response status is 400.
*** Otherwise the response status is 204 and the body is empty.
*** Use this function to check you have access to the private key which corresponds to the public key
    that the server has associated with `*id*`.
* `/perk/`
** POST requests:
*** The request body should contain an issuer ID (obtained from a previous GET or PUT
    request to `/cred/*id*/`) and an https://apowers313.github.io/fido2-lib/Fido2Lib.html#assertionResult[assertion
    result] generated by `navigator.credentials.get` in a browser.
*** The challenge used to generate the assertion result should be an _unsigned_ JWT. The request body is
    passed to https://github.com/davedoesdev/authorize-jwt#authorizejwtprototypeauthorizeauthz_token-allowed_algs-cb[authorize-jwt] for verification.
*** If the issuer ID does not identify a public key or the assertion result does not verify using the public key
    identified by the issuer ID then the response status is 400.
*** Otherwise `webauthn_perk_options.perk_options.handler` is called.
** GET requests:
*** The request should have a single parameter, `assertion_result`, containing the same JSON-encoded data
    required by POST requests to `/perk/` (issuer ID and assertion result). 
*** The `assertion_result` is passed to the POST route handler for `/perk/`.
*** The response is the same as described above for POST requests for `/perk/`.

JSON schemas for these routes can be found in link:dist/schemas.js[].

== Installation

[source,bash]
----
npm install webauthn-perk
----

== Licence

Unlicenced

== Test

[source,bash]
----
grunt test
----

== Lint

[source,bash]
----
grunt lint
----

== Coverage

[source,bash]
----
grunt coverage
----

https://istanbul.js.org/[Istanbul] results are available 
https://gitlab.com/davedoesdev/webauthn-perk/builds/artifacts/master/download?job=ci"[here].